# Use the official Apache HTTP Server image from Docker Hub
FROM httpd:2.4

# Corrected COPY command to match the directory structure
#COPY HW1_Part2.html /usr/local/apache2/htdocs/

# Copy your custom HTML file to the default document root of Apache
COPY ./ /usr/local/apache2/htdocs/
#>>>>>>> Stashed changes
